feat: React Navigation and Routes
alcurvelo/widergy-mobile-training pull request #2
Opened 2021-06-04 20:37 UTC by alcurvelo

## Summary
Perform:
* Navigation
 -Routes
 -History component.
* Change of organization of the screens.
* Visual improvements.

## Screenshots:
I add the views of the app.

![Home](https://user-images.githubusercontent.com/83591486/120859943-4e393580-c55b-11eb-8d60-2dc5bfcde78c.png)
![History](https://user-images.githubusercontent.com/83591486/120859959-52fde980-c55b-11eb-9674-49cf65cfeb2c.png)
![About](https://user-images.githubusercontent.com/83591486/120859967-55604380-c55b-11eb-9876-5db3594d4254.png)

## Trello Issue
[Rutas en la App](https://trello.com/c/Vig81l00/24-rutas-en-la-app)

2021-06-08 14:52 UTC, lucawidergy requested changes
Eto, esta bastante bien. Pero recorda siempre ajustarte a lo que pide la card, no hacer ni mas ni menos. En este caso en particular, hiciste una vista principal y se pedia que entre directo a la calculadora y tenga el boton de historial. Ahora, en la card de integracion esa vista no la vas a tener por lo que fue tiempo invertido que realmente no tiene sentido. Te recomiendo que de ahora en mas, cuando arranques un nuevo desarrollo leas la card y evacues cualquier duda o consultes a ver si entendiste correctamente lo pedido.

2021-06-08 14:52 UTC, lucawidergy commented on src/app/navigation/AppNavigator/index.js
> +            headerTintColor: 'white',
estas opciones, las estas repitiendo abajo denuevo. Deberias tener una opciones x default. Y en caso particulares editarlo

2021-06-08 14:52 UTC, lucawidergy commented on src/app/screens/About/index.js
> +        source={require('../../assets/logo.png')}
no deberias usar require, sino importarlo arriba como los componentes.
import logo from '../../assets/logo"

2021-06-08 14:52 UTC, lucawidergy commented on src/app/screens/Home/components/Button/styles.js
> +    display: 'flex',
esto creeria q no es necesario

2021-06-08 16:06 UTC, lucawidergy commented on src/app/screens/History/index.js
> +  let expressions = ['24 + 36 = 60', '25 - 275 = -250'];
const

2021-06-08 19:32 UTC, alcurvelo commented on src/app/screens/About/index.js
> +        source={require('../../assets/logo.png')}
Ok, modifico y aplico de esa manera.

2021-06-08 19:33 UTC, alcurvelo commented on src/app/navigation/AppNavigator/index.js
> +            headerTintColor: 'white',
Ok, hice una constante de opcion por defecto en las que repito.

2021-06-08 19:38 UTC, alcurvelo commented on src/app/screens/Home/components/Button/styles.js
> +    display: 'flex',
Solo el `display: flex`, si quito el `flex: 1` me cambia el tamaño de los botones, el color background es el que se muestra por defecto (con el color que quedan los numéricos).

2021-06-08 19:45 UTC, alcurvelo commented on src/app/screens/History/index.js
> +  let expressions = ['24 + 36 = 60', '25 - 275 = -250'];
Tengo un problema grave con eso, lo hago sin darme cuenta, ahí lo cambio.

2021-06-08 19:47 UTC, alcurvelo commented
Respecto a la pantalla About, realmente ya la tenia hecha de lo que había hecho anteriormente con el Drawer, tan solo lo deje, no considere que fuese a causar lió :/ . Pero si lo entendí, no haré otra cosa adicional.

2021-06-11 17:09 UTC, lucawidergy commented
@alcurvelo Acabo de probarlo y no esta el boton de historial, no hay navegacion D:

2021-06-16 12:52 UTC, lucawidergy approved these changes

2021-06-16 12:54 UTC, taltrui approved these changes

2021-06-16 12:54 UTC, taltrui commented on src/app/screens/History/styles.js
> +    flex: 0.94,
This very precise numbers are more often than not very problematic since you can encounter a very broad type of smartphones with different screen sizes.

2021-06-16 12:57 UTC, merged