feat: Adding services to the APP
alcurvelo/widergy-mobile-training pull request #4
Opened 2021-06-14 14:39 UTC by alcurvelo

## Summary

* The api service was added: https://widergy-training-api.herokuapp.com/. Through the respective documentation.
* The authorization screen (logging and registration), service, actions and reducers was added.
* Reactotron configuration, to better visualize the store data and the order of actions.

## Test Cases:
* The first screen is the login and registration, so you can proceed with any of them.
* Once inside the calculator, you can save, edit, and delete one or all of the expressions.
* Finally there is the session close button on the upper right.

## Screenshots:
I add the imagenes of the new screens.

![login](https://user-images.githubusercontent.com/83591486/121910140-fa6ddf80-cd04-11eb-86c7-ef494c2d7e5a.png)
![register](https://user-images.githubusercontent.com/83591486/121910155-fd68d000-cd04-11eb-9c9e-e2efb88ce0a8.png)

## Trello Issue
[Agregando servicios a la APP](https://trello.com/c/1WCkBwsl/25-agregando-servicios-a-la-app)

2021-06-15 19:51 UTC, lucawidergy requested changes
me falta terminar de revisarlo :) mañana sigo

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/actions.js
> +      //Si agrega la expression, manda un true para que reload cambie y vuelva a pedir las expresiones.
no, para esto podes usar una callback

2021-06-15 19:51 UTC, lucawidergy commented on src/app/navigation/AppNavigator/index.js
> +import actionsAuth from '../../redux/auth/actions';
generalmente ponemos el nombre al revés :P  authActions

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/auth/actions.js
> +    if (token !== false) {
```suggestion
    if (!token) {
```

2021-06-15 19:51 UTC, lucawidergy commented on src/app/navigation/AppNavigator/index.js
> +    dispatch(actionsAuth.userLoged());
el nombre no es del todo descriptivo, hasta tuve que ir a ver que hacia la funcion :P. Yo le ponfria getSavedToken o algo asi.

2021-06-15 19:51 UTC, lucawidergy commented on src/app/navigation/AppNavigator/index.js
> +            <>
Fragment

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/actions.js
> +          response.data.data !== undefined ? response.data.data : [],
no deberia pasar est0. En todo caso la api deberia devolverte un array vacio. Te viene undefined?

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/actions.js
>      if (response.ok) {
y si falla el servicio? que hacemos?

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/actions.js
> +  deleteHistoryForId: idHistory => async dispatch => {
```suggestion
  deleteHistoryById: idHistory => async dispatch => {
```

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/actions.js
>      if (history.length > 0) {
esta condicion, en realidad no deberia ir aca. Sino que el boton este deshabilitado y no se pueda llamar al servicio

2021-06-15 19:51 UTC, lucawidergy commented on src/app/redux/history/reducer.js
> +      /* Sí recibiera el id cuando guardara la expresión, hiciera esto.
porque esta esto comentado?

2021-06-15 19:52 UTC, lucawidergy reviewed
Si pones un user que no existe queda el loading infinito

![image](https://user-images.githubusercontent.com/57682014/122114712-fbcd0400-cdf9-11eb-8668-561e1f0a2adf.png)

2021-06-16 13:42 UTC, lucawidergy requested changes
ahora si. Ahi van las correcciones!

2021-06-16 13:42 UTC, lucawidergy commented on src/app/redux/auth/actions.js
> +      delete user.confirmPassword;
trata de no usar delete. De echo, no es inmutable

2021-06-16 13:42 UTC, lucawidergy commented on src/app/redux/auth/actions.js
> +    if (user.password === user.confirmPassword) {
como habiamos dicho, esto no deberia estar aca. La parte de validacion deberia estar previamente hecha y no en el action creator. Sino que no te deje hacer submit si las contaseñas no eran iguales

2021-06-16 13:42 UTC, lucawidergy commented on src/app/redux/history/actions.js
>      payload: [],
no, en este caso no iria payload. Sino que en el reducer deberias poner el valor por default

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/components/Input/index.js
> +      value={values[nameInput] ? values[nameInput] : ''}
```suggestion
      value={values[nameInput]  ||  ''}
```

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/index.js
> +          <>
fragment

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/index.js
> +          <>
fragment

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/index.js
> +            <Input
yo estoy viendo codigo repetido acá. los primeros 2 input son identicos. Como harias para sacar la condicion con el ? y que solo se renderice el ultimo field si se cumple una condicion?. el titulo tb, podes hacer que el texto cambie de acuerdo a esa condicion.

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/index.js
> +        <TouchableOpacity
aca, podrias deshabilitar el boton, si las contaseñas no son correctas

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/Auth/styles.js
> +//dorado #ffb200
```suggestion
```

2021-06-16 13:42 UTC, lucawidergy commented on src/app/screens/History/ExpressionContainer/index.js
>    let buttons = retrieveButtons(display, setDisplay, setTypeExpression);
por qué let?

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/AuthService.js
> +  singIn: async user => {
sin async, y sin await. y sin escribir return :B

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/AuthService.js
> +  singIn: async user => {
signIn: user=> api.post()

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/AuthService.js
> +  singIn: async user => {
replicalo en todos

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/storagePersist.js
> +      return false;
en todo caso null y hace un throw de un error

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/storagePersist.js
> +      return false;
evita mezclar tipos. SI el try funciona no devolves nada. pero si falla devolves false? no tiene sentido

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/storagePersist.js
> +      return false;
idem

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/storagePersist.js
> +      return false;
idem

2021-06-16 13:42 UTC, lucawidergy commented on src/app/services/storagePersist.js
> +      return false;
idem

2021-06-16 14:30 UTC, alcurvelo commented on src/app/navigation/AppNavigator/index.js
> +import actionsAuth from '../../redux/auth/actions';
Ok, cambiado

2021-06-16 14:30 UTC, alcurvelo commented on src/app/redux/auth/actions.js
> +    if (token !== false) {
Cierto, cambiado tambien

2021-06-16 14:30 UTC, alcurvelo commented on src/app/navigation/AppNavigator/index.js
> +    dispatch(actionsAuth.userLoged());
jajaja tienes razón, tomo lo sugerido y hago el cambio.

2021-06-16 14:30 UTC, alcurvelo commented on src/app/navigation/AppNavigator/index.js
> +            <>
cambiado

2021-06-16 14:31 UTC, alcurvelo commented on src/app/redux/history/actions.js
>      if (response.ok) {
Entiendo, cambiado

2021-06-16 14:31 UTC, alcurvelo commented on src/app/redux/history/actions.js
> +  deleteHistoryForId: idHistory => async dispatch => {
cambiado

2021-06-16 14:32 UTC, alcurvelo commented on src/app/redux/history/reducer.js
> +      /* Sí recibiera el id cuando guardara la expresión, hiciera esto.
Por que realmente no esta guardando nada, por que hace un pedido a la api pidiendo todas expresiones

2021-06-16 14:33 UTC, alcurvelo commented on src/app/redux/history/reducer.js
> +      /* Sí recibiera el id cuando guardara la expresión, hiciera esto.
en espera que el tano devuelva el id en un futuro diria xd

2021-06-16 14:33 UTC, alcurvelo commented on src/app/redux/history/actions.js
>      if (history.length > 0) {
Entiendo, hice los cambios involucrados

2021-06-16 14:45 UTC, alcurvelo commented on src/app/redux/history/actions.js
> +      //Si agrega la expression, manda un true para que reload cambie y vuelva a pedir las expresiones.
Vale, reestructure esto

2021-06-16 14:52 UTC, alcurvelo commented on src/app/redux/history/actions.js
> +          response.data.data !== undefined ? response.data.data : [],
![image](https://user-images.githubusercontent.com/83591486/122241778-3174fa00-ce99-11eb-8756-e2b8d93d5d30.png)
 Esta devolviendo un objeto y me rompe todo xd

2021-06-16 15:25 UTC, alcurvelo commented on src/app/redux/auth/actions.js
> +      delete user.confirmPassword;
Listo, cambio realizado

2021-06-16 15:25 UTC, alcurvelo commented on src/app/redux/auth/actions.js
> +    if (user.password === user.confirmPassword) {
Perfecto, cambio realizado

2021-06-16 15:39 UTC, alcurvelo commented on src/app/redux/history/actions.js
>      payload: [],
Perfecto, cambio hecho

2021-06-16 15:42 UTC, alcurvelo commented on src/app/screens/Auth/components/Input/index.js
> +      value={values[nameInput] ? values[nameInput] : ''}
hecho

2021-06-16 15:42 UTC, alcurvelo commented on src/app/screens/Auth/index.js
> +          <>
idem

2021-06-16 15:42 UTC, alcurvelo commented on src/app/screens/Auth/index.js
> +          <>
idem

2021-06-16 15:53 UTC, alcurvelo commented on src/app/screens/Auth/index.js
> +            <Input
Si tienes razón, ya hice ambas modificaciones.

2021-06-16 15:55 UTC, alcurvelo commented on src/app/screens/Auth/index.js
> +            <Input
` {!screenView && (
            <Input
              placeholder="Confirma la contraseña"
              nameInput="confirmPassword"
              onChange={readInput}
              secureTextEntry={true}
              values={values}
            />
          )}`.
Quedo así al final.

2021-06-16 16:01 UTC, alcurvelo commented on src/app/screens/Auth/index.js
> +        <TouchableOpacity
Entiendo, ya lo agregue.

2021-06-16 16:07 UTC, alcurvelo commented on src/app/screens/Auth/styles.js
> +//dorado #ffb200
Ups, se me paso que había copiado ahí, gracias

2021-06-16 16:08 UTC, alcurvelo commented on src/app/screens/History/ExpressionContainer/index.js
>    let buttons = retrieveButtons(display, setDisplay, setTypeExpression);
Cambiado, tiene que ser const

2021-06-16 16:15 UTC, alcurvelo commented on src/app/services/storagePersist.js
> +      return false;
Ok, entendido y hecho.

2021-06-16 16:34 UTC, alcurvelo commented on src/app/services/storagePersist.js
> +      return false;
Entiendo, en caso que fallen, solo mande a mostrar el mensaje en consola.

2021-06-16 16:34 UTC, alcurvelo commented on src/app/services/storagePersist.js
> +      return false;
igual

2021-06-16 16:34 UTC, alcurvelo commented on src/app/services/storagePersist.js
> +      return false;
igual

2021-06-16 16:34 UTC, alcurvelo commented on src/app/services/storagePersist.js
> +      return false;
igual

2021-06-16 16:34 UTC, alcurvelo commented on src/app/services/AuthService.js
> +  singIn: async user => {
Hecho

2021-06-16 16:38 UTC, alcurvelo commented
Respecto al error del warning, busque como sacarlo, pero la verdad no encontré como, antes de leerlo ya estaba buscándolo, pero no encuentro que es lo que seria. Cuando puedas me gustaría mirarlo.

2021-06-17 14:18 UTC, lucawidergy commented on src/app/config/stylesUtilityGo.js
> +import { UTProgressBar } from '@widergy/mobile-ui';
en realidad no necesitabas agregar todo el theme, solo tenias que crear el archivo theme y podias exportar un objeto vacio.

2021-06-17 14:31 UTC, lucawidergy commented on src/app/redux/history/actions.js
> +          response.data.data !== undefined ? response.data.data : [],
Oka, levanta el punto en donde estes anotando las cosas para el training asi lo corregimos

2021-06-17 14:51 UTC, lucawidergy approved these changes
Eto, esta bien.

Te falto hacer algunas validaciones con respecto al login, pero no creo que tengas que demorar mas y hacerlas aca sino tenerlas en cuenta para cuando agregues redux form:

1- que no se pueda hacer submit si falta email y/o contraseña
2- en registracion, al comparar las contraseñas no dejas hacer submit pero no informas al user que esta poniendo contraseñas distintas entonces nunca se entera. Vos podes dejar hacer submit si las contraseñas son distinta y ahi decir che no, son distintas pero nunca haber llamado a la accion de registraccion de redux

2021-06-17 18:55 UTC, alcurvelo commented on src/app/config/stylesUtilityGo.js
> +import { UTProgressBar } from '@widergy/mobile-ui';
Entiendo, ahí lo realice.

2021-06-18 18:33 UTC, taltrui approved these changes

2021-06-22 18:19 UTC, merged