feat: Adding Forms to the APP
alcurvelo/widergy-mobile-training pull request #5
Opened 2021-06-17 19:18 UTC by alcurvelo

## Summary

* Redux-form has been added to the store.
  - it was implemented in the auth screen.

## Test Cases:
* It can be tested by validating that it is an email and a warning has been added so that the password is at least 8 characters long.
* Reactotron is available to look at the actions.
* Email is normalized to lower case.

## Screenshots:
I add the imagenes of the errors and warnings.

![login](https://user-images.githubusercontent.com/83591486/122459252-1680b380-cf87-11eb-8ab7-3341b9d3dd18.png)
![register](https://user-images.githubusercontent.com/83591486/122459255-184a7700-cf87-11eb-8e0b-1071156468e9.png)

## Trello Issue
[Agregando Forms a la APP](https://trello.com/c/IlrzkOzU/26-agregando-forms-a-la-app)

2021-06-18 14:02 UTC, lucawidergy requested changes
rompe al hacer submit
![image](https://user-images.githubusercontent.com/57682014/122572909-97da5380-d024-11eb-851a-88ce6a2d6396.png)

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/index.js
> +              values.password === values.confirmPassword
no, esto deberias correr una validacion en confirmpassword field y al ser distintas te inhabilitaria el boton por el echo de haber errores

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const fieldsNewUser = [
mayusculas el nombre. Es una constante

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const fieldsLogin = [
mayusculas y snake case , es una constante

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const propertiesByTypeField = {
idem

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/components/renderField/index.js
> +      {touched &&
mensaje deberias mostrar solo cuando hay un error. O cuando es invalid por ejemplo. Pero no cuando esta touched nomas. Porque si no lo toque y le doy al submit, debe hacer submit pero saltar las validaciones

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/index.js
> +        disabled={
se deshabilita si es invalido y ademas se le dio a submit y fallo

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/validate.js
> +export const validate = ({ email, password, confirmPassword = false }) => {
esto deberian ser todas funciones separadas

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/validate.js
> +export const warn = ({ email, password, confirmPassword = false }) => {
estas tambien, son validaciones. Y no wanings. El email no tiene porque tener mas de 8 caractares.

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/validate.js
> +  if (confirmPassword && confirmPassword.length < 8) {
esta tampoco tiene sentido, si password tiene q tener 8 caractares y confirm password tiene que ser igual a password decanta por si solo

2021-06-18 14:02 UTC, lucawidergy commented on src/app/screens/Auth/components/AuthForm/normalizers.js
> +export const lowerCaracter = value => value && value.toLowerCase();
```suggestion
export const lowerCaracter = value => value?.toLowerCase();
```

2021-06-18 14:26 UTC, alcurvelo commented
Ok, el error era por que estaba llamando a `AuthForm` sin pasarle un onSubmit, lo cual al no estar usando no lo veía necesario, pero lo saque al final antes del PR y no volví a probar. Corregido.

2021-06-18 14:27 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/index.js
> +              values.password === values.confirmPassword
Ok, hecho

2021-06-18 14:29 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const fieldsNewUser = [
Cierto, aplicado

2021-06-18 14:31 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const fieldsLogin = [
idem

2021-06-18 14:31 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/constants.js
> +export const propertiesByTypeField = {
cambiado

2021-06-18 14:34 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/validate.js
> +  if (confirmPassword && confirmPassword.length < 8) {
Tiene sentido, quitado, gracias

2021-06-18 14:34 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/validate.js
> +export const warn = ({ email, password, confirmPassword = false }) => {
Ok perfecto

2021-06-22 16:05 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/normalizers.js
> +export const lowerCaracter = value => value && value.toLowerCase();
cambiado

2021-06-22 16:06 UTC, alcurvelo commented on src/app/screens/Auth/components/AuthForm/validate.js
> +export const validate = ({ email, password, confirmPassword = false }) => {
hecho

2021-10-05 15:59 UTC, merged